# This file generates the GitHub Actions matrix
include:
  # Standard Corne with Nice!Nano
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne-left
  - board: nice_nano//zmk
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne-right
  # Eyelash Corne
  - board: eyelash_corne_left
    shield: nice_view
    artifact-name: eyelash-left
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: eyelash-right
  # TOTEM Wireless with XIAO BLE
  - board: xiao_ble//zmk
    shield: totem_left
    snippet: studio-rpc-usb-uart
    artifact-name: totem-left
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem-right
  # Settings reset
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings-reset-xiao
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings-reset-nano
