services:
  zmk:
    image: zmkfirmware/zmk-build-arm:stable
    restart: "no"
    volumes:
      - zmk-west:/west
      - ../../:/zmk-config
      - ../../.cache/local:/build
    entrypoint: ["/zmk-config/scripts/docker/build-zmk.sh"]

  qmk:
    image: ghcr.io/qmk/qmk_cli:latest
    restart: "no"
    volumes:
      - qmk-firmware:/qmk_firmware
      - ../../:/qmk-userspace
      - ../../.cache/local:/build
    working_dir: /qmk-userspace
    entrypoint: ["/qmk-userspace/scripts/docker/build-qmk.sh"]

volumes:
  zmk-west:
  qmk-firmware:
