name: build-qmk
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  qmk:
    if: ${{ !vars.ACT || vars.RUN == 'qmk' }}
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
